# Generated by Django 4.0.1 on 2022-01-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetings_delete_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='dated',
            new_name='date',
        ),
    ]
